### ISSUE TITLE
Universal-starter and sass

### ISSUE THREAD

**Issue by HonnKing** [angular/universal-starter#259] opened 2016-11-17 11:02 UTC
Anyone have an idea what would need to be done for universal-starter to work with sass? I fiddled around for a while with it, adding loaders for sass and scss files, but being new to both webpack and ngc it did not go well. :) 

I am assuming it's not supported at the moment (or am I just doing something wrong)?

**Comment by kuldeepkeshwar** [comment] 2016-11-17 11:10
@HonnKing I can give it a try , we are using it in our current project

**Comment by MarkPieszak** [comment] 2016-11-17 12:06
Setting up SASS is fairly easy, but I haven't tried combining it with AoT, I'm wondering how that would work out.

**Comment by antiPoP** [comment] 2016-11-17 16:25
I added SASS following https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-SCSS-in-components and it works in dev mode but for production builds sass does not work at all (neither client nor server side rendering).

It would also be interesting to add support for a global SASS files.

**Comment by MarkPieszak** [comment] 2016-11-17 16:45
One problem is that AoT currently doesn't work with SASS (note: https://github.com/angular/universal-starter/pull/97#issuecomment-254881420)

But yes all you should need is:

    // SASS files
    { test: /\.scss$/, loaders: ['raw-loader', 'sass-loader?sourceMap'] },

But if I remember correctly, you want `ViewEncapsulation.None` on your ROOT App component. That should do the trick.

    encapsulation: ViewEncapsulation.None

**Comment by kuldeepkeshwar** [comment] 2016-11-17 17:13
@MarkPieszak we can use `ExtractTextPlugin` to create a css containing global css for
`ViewEncapsulation.None `

**Comment by antiPoP** [comment] 2016-11-17 19:31
Disabling AoT in `webpack.prod.config` fixes the issue. 

Setting `ViewEncapsulation.None` in `app.component.ts` seems to work too, but doing so I get the following error each in the server console each time I run the app: 

`[0] EXCEPTION: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'favicon.ico'`

**Comment by HonnKing** [comment] 2016-11-18 08:00
Thanks for the suggestions, but I think I was a bit unclear in the question. I specifically want sass with AoT. Using sass otherwise is as you have pointed out easy.

One way to use sass with AoT is to point components to css files and have those generated from sass, but that ends up being two separate builds and king of messy in development. I'm thinking that there probably is a way to point directly to the sass files and then let webpack to grab them, convert them to css and inject them before ngc starts. Similar to what angular-cli does (but they don't have AoT yet).

Also `ViewEncapsulation` only figures into it if you want to build a single css file for the entire app, and that is not the only way to use sass. Nor is it, I would argue, a good way to write css for Angular 2 apps.

**Comment by antiPoP** [comment] 2016-11-18 08:45
+1 for SASS with AoT

Meanwhile I'm trying to run the starter without AoT. I cloned the repo and replaced `server.aot` with `server` and `client.aot` with `client` in `webpack.prod.config`.

Then I did `npm run build:dist` and `npm run server`. In the browser I find this error: 

`main.bundle.js:12 Uncaught Error: No provider for t!`

**Comment by John0x** [comment] 2016-11-18 12:33
You could just have your scss files in the folders and use node-sass to compile them to css. Then just import the css files in your components. Should work, right?

**Comment by antiPoP** [comment] 2016-11-18 13:37
Right, but as @HonnKing explained, this is not an optimal solution.

**Comment by MarkPieszak** [comment] 2016-11-18 14:45
At the moment AoT itself can't support it, but I'm sure it'll be something that will be fixed soon!

**Comment by gdi2290** [comment] 2016-11-18 15:14
AoT can't support it. We would have to compile all scss to css then run AoT or use scss outside of Angular and lose out on the css scope per component

**Comment by antiPoP** [comment] 2016-11-18 17:34
Would be possible to build production without AoT until a fix is released? I have tried disabling it as described in https://github.com/angular/universal-starter/issues/259#issuecomment-261478492 but it didn't worked.

**Comment by gdi2290** [comment] 2016-11-18 18:17
for production in Universal you have to use AoT otherwise you run into memory leaks with Angular core's jit

**Comment by josiah1888** [comment] 2016-11-18 21:06
@gdi2290 

Are the memory leak issues a temporary bug that will be fixed soon? Or are we going to strictly have to use AoT in production now?

**Comment by gdi2290** [comment] 2016-11-18 23:06
The performance improvements are too high not to use AoT. The experience for AoT will get better with time but right now Angular 2 was designed with AoT in mind. I updated universal-starter to have AoT so it's easier to start off with it. If you have a hard time understanding why you have to write things a certain way for AoT think of it this way.



with AoT the computer is generating a class for each component and ngmodule so

[computer generated] -> [user generated]

with AoT angular is creating a host class that imports your code
`wat.ts`
```
// you wrote this code
var yolo = 'yolo'l

@NgModule({ /* ... */ })
class WatModule {
  constructor() {
    condole.log(yolo);
  }
}
```
`wat.ngfactory.ts`
```typescript
import * as Wat from './wat';

class NgFactory {
  _wat: Wat;
  get wat() {
    // return instance or create it
    if (this._wat) return _wat;
    this._wat = new Wat();
    return this._wat;
  }
}

// during bootstrap
var moduleRef = new NgFactory()
moduleRef.wat // <-- your module instance
```
Angular generates another file to ensure that whatever code you wrote still works. This is also why sometimes you need to export functions used in the metadata. Again the difference in performance is 5-10x so it's worth it

**Comment by John0x** [comment] 2016-11-19 11:10
Hey, there seems to a problem with using css and the styleUrls parameter.

I have a component with the following:
````
Component with:
styleUrls: ['./home.component.css']

home.component.scss:
home {
  background-color: black;
}
````

The home.component.scss get's compiled to css bei node-sass before I run webpack. The component imports the generated css file.
The rendered html file contains the correct data:
````
home[_ngcontent-33]{background-color:black}

 <app>
    <router-outlet></router-outlet><home _nghost-33="">
  Home component
  </home>
  </app>
````

But it looks like that once the script is rerun on the client the html element home get's a different annotation(?) since it looks like the following once I inspect it in chrome:
````
<app>
    <router-outlet></router-outlet><home _nghost-4f39-33="">
  Home component
  </home>
  </app>
````

Which breaks my css code.

Is there any solution to this?

**Comment by John0x** [comment] 2016-11-19 14:15
Ah, seems like the ViewEncapsulation.Emulated flag was the problem. Setting it to None fixed it.

**Comment by MarkPieszak** [comment] 2016-11-19 15:46
yeah we'll have to add that to our Gotchas list, that one is very important actually, and a hard one to spot!

**Comment by samvloeberghs** [comment] 2016-11-20 12:37
I'm highly surprised that SASS isn't working with AoT as I don't see the impediment.. The SASS gets compiled to CSS/text before binding it to a component right? So what is the drawback here.. Not seeing it :)

**Comment by HonnKing** [comment] 2016-11-21 08:26
The drawback is that the compiler explodes :)

AoT compilation happens (or seems too happen, I'm no expert at all) before the whole sass/css part of the build. So when the compiler runs it finds the sass/scss file and not normal css, and it can't handle it.

My solution for now was just to use node-sass to compile the sass files first, then run the build. Not an awesome setup, but a working one at least.

**Comment by gdi2290** [comment] 2016-11-21 14:36
yeah the current solution is to compile sass before running AoT then Webpack and for components point to the compiled version of css

**Comment by kuldeepkeshwar** [comment] 2016-11-28 10:07
created a pr for sass support https://github.com/angular/universal-starter/pull/281

**Comment by haia212** [comment] 2017-01-19 12:09
Hello ! I am trying to use SASS with universal (no AoT). I did as suggested by @antiPoP with his link https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-SCSS-in-components
It works fine except that the app.component.scss is loaded twice. It is exactly the same problem that is described here https://stackoverflow.com/questions/37375003/angular2webpack-loads-styles-twice-at-the-head
In my simple understanding, I think it's because the app.component is rendered on the server (so  the corresponding scss is added to the <head>) and then rendered again on the client (so the corresponding scss is added to the <head> again). Am I missing something ? Does anyone else have the same issue ?
Can anyone have a solution ?

**Comment by MarkPieszak** [comment] 2017-01-20 01:19
Does using ViewEncapsulation.None on the root App component help? @haia212

**Comment by haia212** [comment] 2017-01-20 08:05
The ViewEncapsulation.None allow the css to be applied to the all app. It works fine that way.
The problem I am having is that I have (client side) two `<style>` tags in my `<head>` containing exactly the same code. 

After some digging, it is the case for every components that are rendered server side. It's like the document file created by the server already contains the `<style>` tags and then, the client includes the same `<style>` tag.

For example, I have a component rendering a google map that is not rendered on server side (I use `<app-map *ngIf="isBrowser">`). The style of this component is added once in the `<head>` but for every components that are rendered both server side and client side (like app.component) the style is included twice in the head.

**Comment by samvloeberghs** [comment] 2017-01-20 08:30
@haia212 if you use viewencapsulation none to style your entire app. you could easily abstract your css outside your angular code and load it as an external file (.css) trough a link tag. This should solve your issue.

**Comment by jeremybviseo** [comment] 2017-02-08 08:38
I faced the same issue yesterday.

According to https://github.com/angular/angular-cli/issues/3399, it seems that ViewEncapsulation.None doesn't work with styleUrls in AOT mode. 

So what I did is :

- Using default viewencapsulation
`encapsulation: ViewEncapsulation.Default`

- Include a single "app.style.css" (note the CSS extension)
`  styleUrls: [
    './app.styles.css'
  ]`

- Create an "app.style.scss" that wrap all my SCSS imports with  /deep/ { ... } (This is an alternative to ViewEncapsulation.None)
```
/deep/ {
  @import "../../node_modules/bootstrap/scss/bootstrap";
  @import "../../node_modules/swiper/dist/css/swiper";
}
```

- Add node-sass as a pre-build command in package.json
```
    "sass": "node-sass src -o src --include-path node_modules --output-style compressed -q",
    "build:prod:ngc": "npm run clean:ngc && npm run sass && npm run ngc && npm run clean:dist && npm run build:prod",
```

Now, it works with AOT.

**Comment by samvloeberghs** [comment] 2017-02-08 09:05
If you use deep for all your components just set view encapsulation none and bind to component selector in scss.. overly use of deep is not good. It should only be used to style child components if you have to..

**Comment by peterpeterparker** [comment] 2017-08-10 08:34
I just did like described in the documentation and it worked for me:

https://github.com/AngularClass/angular-starter/wiki/How-to-include-SCSS-in-components

Respectively:

1. First, install the libs

    npm install node-sass --save-dev
    npm install sass-loader --save-dev

2. in `webpack.common.js` add the configuration in `rules`:

      {
        test: /\.scss$/,
        use: ['raw-loader', 'sass-loader']
      }

3. then in app.component.ts remove

    styles: [
         `h1 {
         color: green;
       }`
     ]

and add
    
    styleUrls: ['./app.component.scss'],
    encapsulation: ViewEncapsulation.None

4. and finally create a new file app.component.scss (on the same level as app.component.ts) containing something like

    h1 {
       color: red;
     }

**Closed** 2017-09-22 20:31 UTC

**Comment by Vandivier** [comment] 2018-01-16 17:42
can we inline svg files by filename?
