### ISSUE TITLE
Router initialNavigation is called twice when bootstrap two components ( SEO related )

### ISSUE THREAD

**Issue by mekya** [angular/universal-starter#192] opened 2016-10-06 16:36 UTC
Hi,
I need to add some meta tags to the head of the app for seo purposes so I bootstrap two components in NgModule one for the <app> tag inside body and one for the <head> tag. It seems ok. There is no problem with that. 

```
@NgModule({
		bootstrap: [ App, Head ],
....

@Component({
  selector: 'app',
  //templateUrl: 'app.html'
  template: '<router-outlet></router-outlet>',
})
export class App { 
...

@Component({
  selector: 'head',
  templateUrl: 'head.html'
})
export class Head {
...
```

However when there is two components in bootstrap, router's initialNavigation function is called twice because callback function is called with APP_BOOTSTRAP_LISTENER  and it makes browser history weird, pushes same locations twice, back button does not work, etc. 

FYI,
Bests
A. Oguz

**Comment by gdi2290** [comment] 2016-10-24 03:02
this is not possible after NgModule but the workaround, for what you want, is to create a SeoService that I will release in this repo later this week. So closing this as it's by design

**Closed by gdi2290** 2016-10-24 03:02 UTC

**Comment by mekya** [comment] 2016-10-27 07:26
I can create a sample code to let you see what is happening if you want to see?

Nevertheless , waiting for your SeoService
