### ISSUE TITLE
How to debug

### ISSUE THREAD

**Issue by gregor-srdic** [angular/universal-starter#655] opened 2018-11-28 18:39 UTC
I have a problem with prerendering and server side rendering using this starter, but I can not find a way how to get more info about the error :S
please help!

```
C:\Users\Uporabnik\Workspace\Sandbox\ibex-universal-starter> npm run serve:ssr

> ibex-web@0.0.0 serve:ssr C:\Users\Uporabnik\Workspace\Sandbox\ibex-universal-starter
> node dist/server

Node Express server listening on http://localhost:4000
ERROR [Error]
ERROR [Error]
ERROR [Error]
ERROR [Error]
ERROR [Error]
ERROR [Error]
```

**Comment by CaerusKaru** [comment] 2018-11-28 18:42
Please provide a minimal reproduction repository. This isn't happening with just the universal-starter for me.

**Comment by gregor-srdic** [comment] 2018-11-28 18:51
Thanks for a response.

I understand, but if there is Error in the console, how can I get more info about it?
Or do you mean, you never get only "Error [Error]" in console?

Is my dependencies list of any help? 
```
"dependencies": {
    "@agm/core": "^1.0.0-beta.5",
    "@angular/animations": "^6.1.8",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/fire": "^5.0.2",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/material": "^6.4.7",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/platform-server": "^6.1.8",
    "@angular/router": "^6.1.0",
    "@ngx-share/core": "^6.0.1",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",
    "core-js": "^2.5.4",
    "firebase": "^5.5.1",
    "hammerjs": "^2.0.8",
    "moment": "^2.22.2",
    "ng2-charts": "^1.6.0",
    "rxjs": "~6.2.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.0",
    "@angular/cli": "~6.2.3",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/googlemaps": "^3.30.13",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  }
```

**Comment by CaerusKaru** [comment] 2018-11-28 19:05
Judging from your dependencies, this is very likely not a problem with the universal-starter, and is instead an issue with one of your dependencies. Since this is an issue tracker, and not a support forum, I am closing this issue. Better avenues for support are Gitter or StackOverflow.

**Closed by CaerusKaru** 2018-11-28 19:05 UTC
Labels: Needs more info
