### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by coderrepo** [angular/universal-starter#542] opened 2018-02-22 11:45 UTC
- Page loading twice and flicking the screen! 
https://ngcoderfirst.firebaseapp.com/
- When I access page url routing to home then back to requested URL. 
Ex : https://ngcoderfirst.firebaseapp.com/career

I have hosted apps in the Firebase hosting platform!

**Comment by CaerusKaru** [comment] 2018-02-25 21:51
Duplicate of https://github.com/angular/angular/issues/15716

**Closed by CaerusKaru** 2018-02-25 21:51 UTC

**Comment by wryly** [comment] 2018-03-05 09:37
This issue is still occurring. angular/angular#15716 was closed with a request to create a new issue with minimal reproduction. This issue does that.

Any updates on a fix for this and angular/angular#15716? Should another issue be submitted?
