### ISSUE TITLE
View flickers when data.json is slow

### ISSUE THREAD

**Issue by AhmedObaidi** [angular/universal-starter#102] opened 2016-06-08 02:46 UTC
If I add a delay to data.json, the view flickers when client side rendering executed. 
```
// Our API for demos only
app.get('/data.json', (req, res) => {
  setTimeout(() => {
    console.log("data.json requested.");
    res.json({
      data: 'This fake data came from the server.'
    });
  }, 2000);
});
```

**Comment by MarkPieszak** [comment] 2016-06-08 12:28
In the `server.ts` file: Do you have `preboot : false` perhaps?
That can create a flicker since there isn't a shadowed copy of the app below it.

**Comment by AhmedObaidi** [comment] 2016-06-08 14:25
I tried with both `preboot : false` and `preboot:  { appRoot: 'app' }`. I observe same behavior in both ways. The html page I get from the server already contains preboot code and script block.
```
<script>
preboot.start();
</script>
```

**Comment by MarkPieszak** [comment] 2016-06-08 14:50
try `true` ? I didn't see a true flicker besides the data going in & out on the page

**Comment by AhmedObaidi** [comment] 2016-06-08 16:21
OK, I just tried it with `preboot : true`, and got same behavior. 
This screencast shows the behavior.
http://screencast.com/t/RxkTgdch71sK

The page first rendered with 
```
Async data call return value:
{
  "data": "This fake data came from the server."
}
```

But when client side angular is bootstraped, it deletes the content before it get the response from the server. Since the server takes 2 seconds to return the response, user can notice the flicker.

```
Async data call return value:
{
}
```
After 2 seconds, the data from the server is rendered back on the page:
```
Async data call return value:
{
  "data": "This fake data came from the server."
}
```

When I "View the Page Source" I can see that the server sent this block:

```
 <strong _ngcontent-ddo-1="">Async data call return value:</strong>
      <pre _ngcontent-ddo-1="">{
  "data": "This fake data came from the server."
}</pre>
```

**Comment by MarkPieszak** [comment] 2016-06-08 16:50
Yes this flicker is supposed to happen unfortunately, the content is actually re-loaded again on the Client-side (and you have that 2 second delay). If you don't want to load async calls on the server-side just do `async: false` in your express settings.

I might be mistaken but I think we'll be adding a cache ability to Universal at some point in the future (to save these xhr calls if desired, so they don't reload on the client-side).

**Comment by gdi2290** [comment] 2016-06-09 08:56
the idea is that you're suppose to cache the api endpoints so when the app bootstraps and makes api calls it will hit the cache first. I need to wire up (again) sending the existing cache down to the client embeded in the index.html so when the client bootstraps the http calls would hit the cache yet again and returns the results

**Comment by AhmedObaidi** [comment] 2016-06-10 16:30
Many thanks Mark and gdi2290. 

Can't we just serialize the model and skip client side rendering until model is changed by user input, timer or server side push notification ?

**Comment by gdi2290** [comment] 2016-06-11 19:21
yeah we can send the results to the client so the client will reuse the response made from the server

**Comment by kuldeepkeshwar** [comment] 2016-07-13 12:27
@gdi2290 any example of reusing the response from the server on client side ?

**Comment by kuldeepkeshwar** [comment] 2016-09-14 09:42
this is still happening with rc7 release

<img width="1345" alt="screen shot 2016-09-14 at 2 45 38 pm" src="https://cloud.githubusercontent.com/assets/10448534/18507350/9be339de-7a8d-11e6-92d6-cbc7f3304b16.png">
<img width="1369" alt="screen shot 2016-09-14 at 2 45 57 pm" src="https://cloud.githubusercontent.com/assets/10448534/18507351/9be81792-7a8d-11e6-99ea-01fc1b687ed1.png">
<img width="1339" alt="screen shot 2016-09-14 at 2 46 09 pm" src="https://cloud.githubusercontent.com/assets/10448534/18507352/9bfea598-7a8d-11e6-97fb-1dd637dab331.png">

**Comment by jeffwhelpley** [comment] 2016-10-03 10:52
This is a duplicate of #139. I am going to close this one and we will just track the issue from 139.

**Closed by jeffwhelpley** 2016-10-03 10:52 UTC
