### ISSUE TITLE
Re-rendering when bootstraping at client

### ISSUE THREAD

**Issue by bhkim526** [angular/universal-starter#139] opened 2016-08-03 00:30 UTC
Using async http is causing the UI flickering when bootstraping at client side since the UI is rendered twice, 1 at server-side and 1 at client-side after each async http call.

So I came up with a home-brewed service which embeds the data from the first http call at server into rendered html so I can skip the second call and use the cached data instead at client side but still the UI is re-rendered and flickers due to the client-side bootstraping.

Is there any way I can skip the second rendering? or am I doing this in wrong way? or there is any better way to do this? should I use precache, primeCache or prime? there is no example or sample I can find on these options though.

**Comment by vidinev** [comment] 2016-08-05 13:51
+1

**Comment by felipedrumond** [comment] 2016-08-09 11:42
I'm having the same issue here. I believe that there should exist a strategy that allows us to configure what is going to run or re-run at the client or not. For instance, if the client has a cart-id cookie, I'd like to re-run a http call to get its cart json and update the view, without bootstraping the whole app at the client.

**Comment by MarkPieszak** [comment] 2016-08-09 14:09
The flicker is something we can look at, there might be something new going on that's causing it. As for the client bootstrapping, it actually needs to render again, since that's how the browser turns it into an actual SPA application, otherwise it's nothing more than rendered html. 

An ideal way to store http calls from the server and use that cached data is still in the works. Is that what you guys mean?

**Comment by abeleshko** [comment] 2016-08-09 16:39
You can see this flicker on the screenshot
![screen shot 2016-08-09 at 9 36 05 am](https://cloud.githubusercontent.com/assets/18040799/17524836/09cb906c-5e15-11e6-8490-cab6d2d563f6.png)

**Comment by kuldeepkeshwar** [comment] 2016-08-09 18:28
flickering duration increases as ajax calls on page increases

**Comment by kuldeepkeshwar** [comment] 2016-08-09 18:31
duplicate #102

**Comment by kuldeepkeshwar** [comment] 2016-09-14 09:23
this is still happening with rc7 release 

1. 

<img width="1345" alt="screen shot 2016-09-14 at 2 45 38 pm" src="https://cloud.githubusercontent.com/assets/10448534/18506516/0d414ade-7a8a-11e6-88d2-41ec2225c7e1.png">

2.

<img width="1369" alt="screen shot 2016-09-14 at 2 45 57 pm" src="https://cloud.githubusercontent.com/assets/10448534/18506517/0d4df068-7a8a-11e6-9fa8-8636f6b5313c.png">

3.

<img width="1339" alt="screen shot 2016-09-14 at 2 46 09 pm" src="https://cloud.githubusercontent.com/assets/10448534/18506515/0d371226-7a8a-11e6-8157-52ed117984fc.png">

**Comment by jeffwhelpley** [comment] 2016-09-14 12:09
We did resolve this issue with the latest updates. The only reason why you would still see this is if `preboot.complete()` is called before the client side http calls are complete. Just so you understand what is going on here. With the new changes, the server view will be displayed until the client view is completely rendered. The switch between the hidden client view and displayed server view only occurs when the client view is complete. So, if you see a flicker it means the client view is not actually complete and doesn't render until after the switch. This would only happen if there is some http call completed AFTER preboot is completed. 

@kuldeepkeshwar, is your code public? Alternatively ping me on g chat tomorrow and I can screen share with you.

**Comment by kuldeepkeshwar** [comment] 2016-09-14 20:35
@jeffwhelpley got your point. but earlier prebootComplete was part of `universal` module.
and if I directly use `prebootClient` from `preboot` module, then  I need to generate inlinePrebootCode and inject in the HEAD section of the server-side template.

Ideally, if `preboot` option is turned on ,universal should out of box generate `inlinePrebootCode` and inject it in the server-side template.

**Comment by gdi2290** [comment] 2016-09-16 19:48
the latest version has preboot via flag in the express config and the client universal module checks for preboot so don't use `UniversalModule.withConfig` as it's an advanced feature now

**Comment by kuldeepkeshwar** [comment] 2016-09-21 18:22
@jeffwhelpley @gdi2290 
I have turned on the preboot flag, but still, the view is flickering. 

repo: https://github.com/kuldeepkeshwar/universal-starter

**Comment by jeffwhelpley** [comment] 2016-09-21 19:12
OK, I will try out your code tonight and let you know.

**Comment by jeffwhelpley** [comment] 2016-09-22 12:38
@kuldeepkeshwar not sure if I am doing this the right way, but I just ran your project and I didn't see any flicker. Can you tell me the exact steps to take to recreate the issue (assume that i have the project running and am on the default page of the app).

**Comment by kuldeepkeshwar** [comment] 2016-09-22 12:54
use localhost:3000/offers/delhi-ncr or navigate to `local` route

**Comment by jeffwhelpley** [comment] 2016-09-22 14:12
@kuldeepkeshwar I need to investigate this a bit further, but I don't think this has anything to do with preboot. It looks like the flash specifically is coming from the snippet behind your router outlet. I need to see why there is the delay in resolving that route because it should resolve immediately on the client, but if you look at the network tab, you can see that the client side route doesn't resolve right away.

**Comment by kuldeepkeshwar** [comment] 2016-09-22 14:27
@jeffwhelpley API call does take time (intentionally made it wait for 1 second to make it look like more real time), but preboot should show server rendered view until client bootstraps completely

**Comment by jeffwhelpley** [comment] 2016-09-22 15:26
Wait..why are you doing the http call in the provider? I am not sure that will work that way. If you move it to the ngOnInit() I would guess this problem will go away.

**Comment by kuldeepkeshwar** [comment] 2016-09-22 15:36
@jeffwhelpley I have to put the http call in the `HomeResolve`(Resolve) because I want data to be available in the component  .
If I make call from ngOnInit() then this will again cause blinking effect until the http call completes

**Comment by emanuelverardi** [comment] 2016-09-23 18:37
Hi! I'm having the same Issue.
I'm using angular2 universal with server rendering and I'm showing a list of videos that came from my API.
As you can see, if is the first time the list of videos are being shown and after a second it desapears and  another http request is made and the list of videos appear again.
This is too bad for UX.    
I tried  to optimize it using ng2-cache to cache my http request data on my session storage. But in the first time that the page is rendered (when I have no cache)  the problem still happen.
Any Idea ?

**Comment by mekya** [comment] 2016-10-01 04:57
Hi,
I'm also having the same issue and it delays project timeline. I can share full source code if you need. 

Bests,
A. Oguz

**Comment by MarkPieszak** [comment] 2016-10-01 14:04
@jeffwhelpley you think this is a preboot issue or just a universal browser platform bootstrap issue that's causing this? We can always do some CSS trick and overlay the client boo trapped version hidden yet on top of the server rendered, then hide the server one and show the other real fast, that might work? Forget what it's doing now.

**Comment by kuldeepkeshwar** [comment] 2016-10-01 15:35
@MarkPieszak @jeffwhelpley 

> We can always do some CSS trick and overlay the client boo trapped version hidden yet on top of the server rendered, then hide the server one and show the other real fast, that might work

is this what preboot does(apart from capturing the event and replaying them) ?

**Comment by jeffwhelpley** [comment] 2016-10-01 15:41
There should not be any flicker. This is a bug. I will be investigating this later today and give more details about the root cause.

**Comment by kuldeepkeshwar** [comment] 2016-10-01 15:45
@jeffwhelpley you can use this [repo](https://github.com/kuldeepkeshwar/universal-starter).
I will be online , let me know if I can help you

**Comment by jeffwhelpley** [comment] 2016-10-03 21:19
OK, so I think we identified the root cause here. Basically, preboot.complete() is running on the client side before all the http calls complete. So, what is happening is:

1. Server view displayed
2. Client view generated in hidden div but http calls not complete
3. Preboot switches views
4. Client view now displayed without data
5. Http calls complete and then do update

That is the momentary flash that you all see. There are two ways to fix this. First, we can delay `preboot.complete()` until all http calls complete. That could be tricky to implement and would only delay further the switch to the client view. The alternative is to get the NgCache working so that the data from the server side is stored in the server view and then used by the client instead of making the same http call again. 

Patrick is working on the NgCache solution now, but just note that this will not be perfect for all use cases since it requires stuffing data in the server view (i.e. and thus if the data is huge it could increase the time to download the server view). So, the workaround for right now is to change AUTO_PREBOOT to false in your providers (i.e. so preboot complete() is not called automatically):

https://github.com/angular/universal/blob/aa4fc4239a6177ab4c70bc8c6af35b84148bbebb/modules/universal/src/browser/universal-module.ts#L45

and then manually call `prebootClient.complete()` once your client side http calls have resolved:

https://github.com/angular/universal/blob/aa4fc4239a6177ab4c70bc8c6af35b84148bbebb/modules/universal/src/browser/universal-module.ts#L91

We will update this issue once there is progress either for NgCache or for something to make it easier to control preboot complete().

**Comment by felipedrumond** [comment] 2016-10-03 22:08
Hi @jeffwhelpley. If I simply delay the preboot by 10 seconds (just to make sure all my requests will be completed), it will blink anyway in the following scenario: [https://github.com/angular/universal/issues/514#issuecomment-251217047](https://github.com/angular/universal/issues/514#issuecomment-251217047)

**Comment by kuldeepkeshwar** [comment] 2016-10-04 12:10
@jeffwhelpley `AUTO_PREBOOT ` is not present in version `2.0.11` .
This was added by  [ Allow for configuring if preboot complete() is called…](https://github.com/angular/universal/commit/aa4fc4239a6177ab4c70bc8c6af35b84148bbebb)

I guess We need to bump the version

**Comment by jeffwhelpley** [comment] 2016-10-04 15:10
Ah, yes. Our mistake. Patrick is about to push in another change and he will publish the new version after that goes in.

**Comment by ignaciolarranaga** [comment] 2016-10-17 14:52
Hi @jeffwhelpley, quick question. I'm following your suggestion regarding AUTO_PREBOOT false and manually call the prebootComplete, but I think I'm having some rookie mistake because I'm having this exception at the client:

`TypeError: angular2_universal_1.prebootComplete is not a function`

Version: 2.1.0-rc.1

What I did is:

* Set AUTO_PREBOOT to false:
```
...
import { AUTO_PREBOOT } from "angular2-universal";

let providers: any[] = [
    {
      provide: AUTO_PREBOOT,
      useValue: false
    }
];
providers.push(appProviders);

@NgModule({
    bootstrap: [ App ],
    declarations: appDeclarations,
    providers: providers,
    imports: [
        UniversalModule, // BrowserModule, HttpModule, and JsonpModule are included
        FormsModule,
        RouterModule.forRoot(appRoutes)
    ]
})
export class MainModule {}
```

* And this after the http loading is complete:

```
...
import { prebootComplete } from "angular2-universal";
...
export class TrimsListingComponent ....
     ngOnInit() {
        this._xxxService.getData...(...)
            .subscribe(
                (response: ResponseTrims) => {
                    this.trims = response.trims;

                    prebootComplete();
                },
                error => console.log("Error: " + error)
            );
    }
```

**Comment by jeffwhelpley** [comment] 2016-10-17 16:44
Try this:

```
var preboot = window.prebootClient();
preboot.complete();
```

**Comment by ignaciolarranaga** [comment] 2016-10-17 20:19
Thanks @jeffwhelpley, actually it did not work:
```
EXCEPTION: window is not defined
ORIGINAL STACKTRACE:
ReferenceError: window is not defined
```

but a similar approach does:
```
declare var preboot;
...
    if (typeof preboot !== 'undefined') {
        preboot.complete();
    }
```

One naive question. Why not to put the preboot.complete() at the end of the async queue by default ?, this will force all the async events to happen before the preboot gets executed and no need to disable it and do it manually, or am I missing something ?

**Comment by jeffwhelpley** [comment] 2016-10-17 20:36
Which async queue are you referring to? You can initiate async events anywhere in your code. You either need to manually coordinate them all through a custom mechanism (in which case you would have to manually call `preboot.complete()` OR you can modify NgZone so that upon initial page load, you want for the app to be stable and then call automatically call `preboot.complete()`. The stabilization strategy is something utilized by Protractor for testing, but it is not perfect and we are still discussing the best way to implement something similar which would work for everyone.

**Comment by ignaciolarranaga** [comment] 2016-10-17 21:07
Well I was thinking on using the zone as you mentioned. If I got it correctly you can catch all the async calls (with the addAsyncListener I guess) on the client inside the zone (as you did on the server) and executing the preboot.complete() after all of them finish, and before the new async events from the client starts.
Or perhaps even better, you can just wait till the same async events that were catch on the server rendering are completed.
Because, If I'm getting it correctly the page received from the server is supposed to be on the same state right ?

I mean, it is like prebooting after all the "pre-render" async events got executed, but I might be missing something fundamental :)

**Comment by jeffwhelpley** [comment] 2016-10-17 22:59
No, the "stable" state on the server and client are fundamentally different. They are similar but generally speaking the client "stable" state can take longer because there may be multiple async calls and push based realtime which is involved. On the server, the rule we have is just 1 iteration of async before we return the response. The client "stable" state is more complicated. But it is certainly possible and something we will explore in the future.

**Comment by ignaciolarranaga** [comment] 2016-10-18 17:34
Thanks for the answer, let me adjust also the way to manually execute the preboot (the previous was actually never executing :)).
It would be:

```
import { prebootComplete } from "angular2-universal";
...
ngOnInit() {
    ....
    ...initialization code...
    ....
    if (typeof prebootComplete != 'undefined') {
        prebootComplete();
    }
}
```

And some kind of flag to not execute preboot again if the component is re-initialized.

In the server will be undefined, and in the client will be defined (that was actually the original problem that I had "_TypeError: angular2_universal_1.prebootComplete is not a function_"

**Comment by jeffwhelpley** [comment] 2016-10-18 18:24
so...as long as you have the preboot client in your client side package (which should be the case if you are including universal), then there should be a global `preboot` object on the window that you can use to call `preboot.complete()`.

**Comment by ignaciolarranaga** [comment] 2016-10-18 18:27
Exactly, the protection is for the server, because prebootComplete is not defined in the server (I think that was the reason for the "_TypeError: angular2_universal_1.prebootComplete is not a function_" that I received originally, I didn't recall it was when the component is rendered on the server).

**Comment by jeffwhelpley** [comment] 2016-10-18 18:36
Yes, preboot on the server is only used to insert the inline JavaScript into the page. You never call complete on the server side.

**Comment by gdi2290** [comment] 2016-10-18 20:44
Here's an example of how to transfer a request made on the server to the client to prime the client cache
https://gist.github.com/gdi2290/1852053c7e629c9ea3720415c381ecd3

**Comment by matiger** [comment] 2016-10-21 15:49
@gdi2290 Well done! This saved my weekend. Thanks bro!

**Comment by gdi2290** [comment] 2016-10-24 03:06
I added the cache to the repo

**Closed by gdi2290** 2016-10-24 03:06 UTC

**Comment by Skillnter** [comment] 2017-09-05 09:36
Any update on flickering issue? The flickering persist...

**Comment by J4cku** [comment] 2017-10-17 19:41
Same for me :(

**Comment by jeffwhelpley** [comment] 2017-10-17 19:50
@J4cku @Skillnter there are two strategies to eliminate flickering now:

1. Re-use data from server side. This will be part of the Angular 5 release, but you can use the latest beta release in your own project if you want to try and get a head start.
2. Utilize Preboot [like this example of Preboot with the Universal Starter](https://github.com/jeffwhelpley/universal-starter-preboot).

Also note that the universal team is looking into what it would take to hydrate the client app instead of re-rendering. This is not a straightforward process and lots of hurdles to overcome, but is a potential for the future.

**Comment by Skillnter** [comment] 2017-11-27 08:21
@jeffwhelpley update for angular 5 is in universal repo but i still see the glitch. I think they have preboot integrated. I am lil' lost here... I know its not a straightforward process and lots of hurdles to overcome. I just want to know for now if its been implemented. I was working on 1st strategy... so i am not sure if i have to continue my work or not.
